### ISSUE TITLE
README md -> org

### ISSUE THREAD

**Issue by kaushalmodi** [Fuco1/orgba#1]
Hello,

As this repo is about Org, I was wondering if you would replace the README.md with README org. 

The GitHub Org renderer is pretty decent (and wider adoption of Org as README markup will help more people know about it, and hopefully improve that Ruby Org mode renderer used by GitHub :)).

**Comment by kaushalmodi** [comment]
Also, I like websites. If you make this into Org mode, reusing the same to create a website from that same source is pretty straightforward.. I do that for my eless (using ox-html) and ox-hugo (using ox-hugo) projects.

**Comment by alphapapa** [comment]
An info page would also be helpful.  I recently learned how to do that from the `org-manual.org` file, and I added it to `org-super-agenda`.  `package.el` installs info pages by default, and Helm even picks them up automatically, so now there's an `helm-info-org-super-agenda` command.  This is basically all I had to do:

```org
** Info export options

#+TEXINFO_DIR_CATEGORY: Emacs
#+TEXINFO_DIR_TITLE: Org Super Agenda: (org-super-agenda)
#+TEXINFO_DIR_DESC: Flexible grouping for the Org Agenda

# NOTE: We could use these, but that causes a pointless error, "org-compile-file: File "..README.info" wasn't produced...", so we just rename the files in the after-save-hook instead.
# #+TEXINFO_FILENAME: org-super-agenda.info
# #+EXPORT_FILE_NAME: org-super-agenda.texi

** File-local variables

# Local Variables:
# before-save-hook: org-make-toc
# after-save-hook: (lambda nil (when (and (require 'ox-texinfo nil t) (org-texinfo-export-to-info)) (delete-file "README.texi") (rename-file "README.info" "org-super-agenda.info" t)))
# org-export-initial-scope: buffer
# End:
```

**Comment by alphapapa** [comment]
And may I suggest using https://github.com/alphapapa/org-make-toc for the table of contents.  :)

**Comment by Fuco1** [comment]
Yea this is a bad habit of mine... org used to suck bad on github for years.  I suppose it's better now.  Do you have some easy way to convert md to org?

**Comment by alphapapa** [comment]
Use org-export.  :)

**Comment by alphapapa** [comment]
Pandoc can do it.
