### ISSUE TITLE
GPLv3 license?

### ISSUE THREAD

**Issue by kaushalmodi** [Fuco1/orgba#3]
How are you licensing this package?

**Comment by alphapapa** [comment]
Geez, Kaushal, are you following me?  Or am I following you...

**Comment by kaushalmodi** [comment]
Heh, I learned about this package on Twitter.

**Comment by alphapapa** [comment]
Oh, where?

**Comment by kaushalmodi** [comment]
Not sure how to interpret that .. Did you mean.. "Really? Twitter? Why Twitter‽"

Or, if that was a genuine "where?", [here][1] :)

[1]: https://twitter.com/Fuco1337/status/1038431505549287424

**Comment by alphapapa** [comment]
No, I don't use Twitter, so I don't follow Matus on it, and I didn't know where to find him on it.

@Fuco1 You should post this kind of stuff to /r/emacs, /r/orgmode, and the org-mode mailing list.  And Planet Emacs.  I watch those with Elfeed and Gnus.  :)

**Comment by Fuco1** [comment]
@alphapapa I don't use reddit but feel free, I also don't use mailing lists because they are silly :D

I have a blog but it's not on planet emacs, I don't know how that works.  I'm very much shit when it comes to self-promotion /shrug.

**Comment by Fuco1** [comment]
@kaushalmodi I think it's in the file header, but I can add the licence file also.

**Comment by alphapapa** [comment]
> I don't use reddit but feel free, 

The /r/emacs and /r/orgmode subreddits are quite active.  :)

> I also don't use mailing lists because they are silly :D

Twitter, though...?  ;)

> I have a blog but it's not on planet emacs, I don't know how that works. 

There's a note on the site, you send someone an email or a PR to the repo, and they add your blog to the feed, it's easy.

**Comment by Fuco1** [comment]
@alphapapa I find that twitter gives me the best exposure with respect to effort, mostly because high-profile people with thousands of followers (bbatsov, nicferrier, jwiegley...) often retweet my stuff.  Occasionally someone links it to reddit then

**Comment by alphapapa** [comment]
I guess I'll have to add their Twitters to my elfeed, then.  :)

**Comment by Fuco1** [comment]
That's the way I used to consume twitter but as far as I can tell twitter has no rss anymore :O Do you have some hack to make that work?

**Comment by alphapapa** [comment]
Oh...well...uh...nevermind, then.  As much as I'd like to follow you and them, I don't want it badly enough to write a Twitter-to-RSS gateway.  :)

BTW, in case it would interest you: Reddit has user comment RSS feeds, so e.g. I see all comments posted on Reddit by John Wiegley, Chris Wellons, Eli Zaretskii, etc.  (And I have an Elfeed entry tagger function that adds the subreddit name to the title, so e.g. "Eli Zaretskii on /r/Emacs/How do I blah blah".)
